### PR TITLE
Sign login design

### PR DESCRIPTION
**Pull request by giurassic**
It's just really basic style stuff so the login/signup looks like the new design showcased today (20.10.2020)

### CODE REVIEW

**Comment by giurassic** [comment]
The commits are NOT detailed due to issues with the original branch being pushed by a different account

**Review by heymage — APPROVED** [review]
Looks good

**Comment by heymage** [comment]
@giurassic After checking it on my machine, the textEdits look a little bit too high. Was this intended?

**Comment by giurassic** [comment]
> @giurassic After checking it on my machine, the textEdits look a little bit too high. Was this intended?

Can you elaborate what you mean by "a little bit too high"

**Review by heymage — APPROVED** [review]

**Pull request merged**
